services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    network_mode: "host"
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://172.24.61.204:11434
    volumes:
      - ollama-webui-data:/app/backend/data
    depends_on:
      - ollama
    network_mode: "host"

volumes:
  ollama-data:
  ollama-webui-data: